---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: inventory-web
  namespace: inventory-demo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/name: inventory-web
spec:
  to:
    kind: Service
    name: inventory-web
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
